# config.yaml
# This file contains the configuration for the CatBoost model training and evaluation.

train_path: ./processed/test_superhost_unpadded.parquet
val_path: ./processed/val_superhost_unpadded.parquet
test_path: ./processed/train_superhost_unpadded.parquet

feature_columns:
  - location_country_code_encoded
  - whois_organization_encoded
  - whois_network_encoded
  - port
  - ipv4

label_column: label
